version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
    volumes:
      - ./db/mysql:/var/lib/mysql

  nodejs:
    build:
      context: ./nodejs
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs/src:/app/src